# Main entrypoint of the workflow.
# Pipeline made to follow best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# ------------------------
#   Load configuration
# ------------------------

#configfile: "config/config.yaml"

# ---------------
#   Load rules
# ---------------

include: "rules/common.smk"
include: "rules/setup.smk"
include: "rules/assemble.smk"
include: "rules/annotate.smk"
include: "rules/classify.smk"
include: "rules/serotype.smk"
include: "rules/summarize.smk"


localrules: mob_init, afp_init, txsscan_init, res_init, checkm_init, ectyper_init, symlink, mash_taxonomy, get_resfinder_species, get_amrfinder_organism, pd_isolate_metadata, summarize_results

# ------------------------------------------
#   Define the target outputs for pipeline
# ------------------------------------------

rule all:
    input:
        os.path.join(output_dir, "SWAM-g_results.xlsx"),
        os.path.join(output_dir, "contig_map.csv"),
        os.path.join(output_dir, "mashtree.nwk")
