# config/slurm/config.yaml

# ----------------------------
#  Set global slurm limits
# ----------------------------

executor: slurm

jobs: 100                       # Max number of simultaneous jobs submitted to slurm
cores: 32                       # Max number of CPUs per job/group
conda-frontend: conda           # conda or mamba 
use-conda: True                 # Enable Conda integration
keep-incomplete: True           # Keep incomplete output to prevent re-computation


# ----------------------------------------------------
#   Set default resources (if not specified in rules)
# ----------------------------------------------------

default-resources:
  slurm_account: "nrsaamr"
  slurm_partition: "'ord'"
  mem_mb: 2000               
  cpus_per_task: 1            
  runtime: "6d"
 
# -----------------------------------------------------------
#  Assign rules: "groups" (run samples in batches)
# -----------------------------------------------------------

groups:
  mobsuite: "mobsuite"
  amrfinderplus: "amrfinderplus"
  resfinder: "resfinder"
  mef: "mobilelementfinder"
  ectyper: "ectyper"
  seqsero: "seqsero"
  txsscan: "txsscan"
  coverage: "coverage"

# -------------------------------------------------------------------------------------------
#  Set the number of connected DAG components a group can span (batch size of each group)
# -------------------------------------------------------------------------------------------

group-components:
  mobsuite: 32
  amrfinderplus: 32
  resfinder: 32
  ectyper: 32
  mobilelementfinder: 32
  seqsero: 32
  txsscan: 32
  coverage: 32

