gtdbtk_db: /work/NRSAAMR/Projects/SWAM/WGS/dbs/release226
checkm_db: /work/NRSAAMR/Projects/SWAM/WGS/dbs/checkm_data
res_db:    /work/NRSAAMR/Projects/SWAM/WGS/dbs/resfinder_db
pt_db:     /work/NRSAAMR/Projects/SWAM/WGS/dbs/pointfinder_db
dis_db:    /work/NRSAAMR/Projects/SWAM/WGS/dbs/disinfinder_db
