cluster: "sbatch --account=nrsaamr --nodes=1 --partition=ord --time=1-00:00:00 --output=/work/NRSAAMR/Projects/SWAM/WGS/slurm/test.%j --ntasks-per-node={threads} --mem={resources.mem_mb}M" 
jobs: 4
default-resources:
  - mem_mb=20000
  - threads=8

gtdbtk_db: /work/NRSAAMR/Software_Databases/gtdb_r220
amrfinder_db: /db/amrfinder
checkm_db: /work/NRSAAMR/Software_Databases/checkm_data
